/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CancelReason { 'reason' : string }
export interface CustomerInquiry {
  'id' : string,
  'customer' : Principal,
  'name' : string,
  'email' : string,
  'message' : string,
  'response' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'totalPriceInCents' : bigint,
  'customer' : Principal,
  'productId' : string,
  'cancellable' : boolean,
  'timestamp' : bigint,
  'upiId' : string,
  'quantity' : bigint,
}
export interface OrderCreate {
  'id' : string,
  'totalPriceInCents' : bigint,
  'customer' : Principal,
  'productId' : string,
  'upiId' : string,
  'quantity' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : { 'reason' : string } } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'priceInCents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteContent {
  'generalDisclaimer' : string,
  'aboutUs' : string,
  'billingPolicy' : string,
  'privacyPolicy' : string,
  'shippingPolicy' : string,
  'officialName' : string,
  'generalInfo' : string,
  'address' : string,
  'contactEmail' : string,
  'phoneNumber' : string,
  'footerContent' : string,
  'termsOfService' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignAdminRole' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string, CancelReason], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderCreate], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<
    [],
    { 'address' : string, 'contactEmail' : string, 'phoneNumber' : string }
  >,
  'getCustomerInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getCustomerOrders' : ActorMethod<[], Array<Order>>,
  'getInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getInquiry' : ActorMethod<[string], CustomerInquiry>,
  'getOrder' : ActorMethod<[string], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteMetadata' : ActorMethod<
    [],
    {
      'privacyPolicy' : string,
      'officialName' : string,
      'termsOfService' : string,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOrderCancellable' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'respondToInquiry' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitInquiry' : ActorMethod<[CustomerInquiry], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateSiteContent' : ActorMethod<[SiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];