/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    dob: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type OrderStatus = {
    __kind__: "shipped";
    shipped: null;
} | {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "confirmed";
    confirmed: null;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CategoryCreate {
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: ExternalBlob;
    images: Array<ExternalBlob>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SiteContent {
    generalDisclaimer: string;
    aboutUs: string;
    billingPolicy: string;
    privacyPolicy: string;
    shippingPolicy: string;
    xUrl: string;
    officialName: string;
    instagramUrl: string;
    generalInfo: string;
    address: string;
    contactEmail: string;
    phoneNumber: string;
    facebookUrl: string;
    footerContent: string;
    termsOfService: string;
}
export interface Category {
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: ExternalBlob;
    images: Array<ExternalBlob>;
}
export interface CarouselSlide {
    order: bigint;
    enabled: boolean;
    visualContent: ExternalBlob;
    urlRedirect: string;
}
export interface CustomerInquiry {
    id: string;
    customer: Principal;
    name: string;
    email: string;
    message: string;
    response?: string;
}
export interface CategoryHeader {
    redirectUrl: string;
    image: ExternalBlob;
}
export interface ProductUpdate {
    media?: ProductMedia;
    inStock?: boolean;
    name?: string;
    description?: string;
    gender?: Gender;
    category?: string;
    priceInCents?: bigint;
}
export interface ShippingAddress {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface BannerMessage {
    order: bigint;
    enabled: boolean;
    message: string;
}
export interface Order {
    id: string;
    status: OrderStatus;
    totalPriceInCents: bigint;
    customer: Principal;
    productId: string;
    cancellable: boolean;
    timestamp: bigint;
    upiId: string;
    quantity: bigint;
    shippingAddress: ShippingAddress;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderCreate {
    id: string;
    totalPriceInCents: bigint;
    customer: Principal;
    productId: string;
    upiId: string;
    quantity: bigint;
    shippingAddress: ShippingAddress;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ProductCreate {
    id: string;
    media: ProductMedia;
    inStock: boolean;
    name: string;
    description: string;
    gender: Gender;
    category: string;
    priceInCents: bigint;
}
export interface ProductMedia {
    video?: ExternalBlob;
    images: Array<ExternalBlob>;
}
export interface CancelReason {
    reason: string;
}
export interface Product {
    id: string;
    media: ProductMedia;
    inStock: boolean;
    name: string;
    createdAt: Time;
    description: string;
    gender: Gender;
    category: string;
    priceInCents: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Gender {
    boys = "boys",
    girls = "girls"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBannerMessage(message: string, order: bigint, enabled: boolean): Promise<bigint>;
    addCategory(categoryInput: CategoryCreate): Promise<void>;
    addCategorySlide(category: string, newSlide: CarouselSlide): Promise<void>;
    addProduct(product: ProductCreate): Promise<void>;
    assignAdminRole(userPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelOrder(orderId: string, cancelReason: CancelReason): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrder(input: OrderCreate): Promise<void>;
    deleteBannerMessage(order: bigint): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    getAllBannerMessages(): Promise<Array<BannerMessage>>;
    getAllCategories(): Promise<Array<Category>>;
    getAllCategoryHeaders(): Promise<Array<[string, CategoryHeader]>>;
    getAllCategorySlides(category: string): Promise<Array<CarouselSlide>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCarouselRedirect(category: string): Promise<string | null>;
    getCategory(name: string): Promise<Category | null>;
    getCategoryCarousel(category: string, carouselNumber: bigint): Promise<Array<ExternalBlob>>;
    getCategoryHeader(categorySlug: string): Promise<CategoryHeader | null>;
    getContactInfo(): Promise<{
        address: string;
        contactEmail: string;
        phoneNumber: string;
    }>;
    getCustomerInquiries(): Promise<Array<CustomerInquiry>>;
    getCustomerOrders(): Promise<Array<Order>>;
    getInquiries(): Promise<Array<CustomerInquiry>>;
    getInquiry(inquiryId: string): Promise<CustomerInquiry>;
    getNewArrivals(): Promise<Array<Product>>;
    getOrder(orderId: string): Promise<Order>;
    getOrders(): Promise<Array<Order>>;
    getProduct(productId: string): Promise<Product>;
    getProducts(): Promise<Array<Product>>;
    getSiteContent(): Promise<SiteContent>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWebsiteMetadata(): Promise<{
        privacyPolicy: string;
        officialName: string;
        termsOfService: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isOrderCancellable(orderId: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    removeCategorySlide(category: string, slideIndex: bigint): Promise<void>;
    reorderCategories(newOrder: Array<string>): Promise<void>;
    reorderCategorySlides(category: string, newOrder: Array<bigint>): Promise<void>;
    respondToInquiry(inquiryId: string, response: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCategoryHeader(categorySlug: string, header: CategoryHeader): Promise<void>;
    setCategoryStatus(name: string, isActive: boolean): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitInquiry(inquiry: CustomerInquiry): Promise<void>;
    toggleCategorySlide(category: string, slideIndex: bigint, enabled: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBannerMessage(order: bigint, message: string, enabled: boolean): Promise<void>;
    updateCarouselRedirect(category: string, redirectUrl: string): Promise<void>;
    updateCategory(name: string, categoryInput: CategoryCreate): Promise<void>;
    updateCategoryCarousel(category: string, carouselNumber: bigint, images: Array<ExternalBlob>): Promise<void>;
    updateCategoryImages(name: string, images: Array<ExternalBlob>): Promise<void>;
    updateCategoryPrimaryImage(name: string, primaryImage: ExternalBlob): Promise<void>;
    updateCategorySlide(category: string, slideIndex: bigint, updatedSlide: CarouselSlide): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateProduct(productId: string, updates: ProductUpdate): Promise<void>;
    updateSiteContent(newContent: SiteContent): Promise<void>;
}
import type { CarouselSlide as _CarouselSlide, Category as _Category, CategoryCreate as _CategoryCreate, CategoryHeader as _CategoryHeader, CustomerInquiry as _CustomerInquiry, ExternalBlob as _ExternalBlob, Gender as _Gender, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductCreate as _ProductCreate, ProductMedia as _ProductMedia, ProductUpdate as _ProductUpdate, ShippingAddress as _ShippingAddress, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBannerMessage(arg0: string, arg1: bigint, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBannerMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBannerMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async addCategory(arg0: CategoryCreate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(await to_candid_CategoryCreate_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(await to_candid_CategoryCreate_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCategorySlide(arg0: string, arg1: CarouselSlide): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategorySlide(arg0, await to_candid_CarouselSlide_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategorySlide(arg0, await to_candid_CarouselSlide_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addProduct(arg0: ProductCreate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_ProductCreate_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_ProductCreate_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdminRole(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: string, arg1: CancelReason): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: OrderCreate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return result;
        }
    }
    async deleteBannerMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBannerMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBannerMessage(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllBannerMessages(): Promise<Array<BannerMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBannerMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBannerMessages();
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategoryHeaders(): Promise<Array<[string, CategoryHeader]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategoryHeaders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategoryHeaders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategorySlides(arg0: string): Promise<Array<CarouselSlide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategorySlides(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategorySlides(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarouselRedirect(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarouselRedirect(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarouselRedirect(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryCarousel(arg0: string, arg1: bigint): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryCarousel(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryCarousel(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryHeader(arg0: string): Promise<CategoryHeader | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryHeader(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryHeader(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<{
        address: string;
        contactEmail: string;
        phoneNumber: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getCustomerInquiries(): Promise<Array<CustomerInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerInquiries();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerInquiries();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiries(): Promise<Array<CustomerInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiry(arg0: string): Promise<CustomerInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_CustomerInquiry_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_CustomerInquiry_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewArrivals(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewArrivals();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewArrivals();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteMetadata(): Promise<{
        privacyPolicy: string;
        officialName: string;
        termsOfService: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteMetadata();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteMetadata();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOrderCancellable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOrderCancellable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOrderCancellable(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async removeCategorySlide(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCategorySlide(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCategorySlide(arg0, arg1);
            return result;
        }
    }
    async reorderCategories(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCategories(arg0);
            return result;
        }
    }
    async reorderCategorySlides(arg0: string, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCategorySlides(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCategorySlides(arg0, arg1);
            return result;
        }
    }
    async respondToInquiry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToInquiry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToInquiry(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCategoryHeader(arg0: string, arg1: CategoryHeader): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCategoryHeader(arg0, await to_candid_CategoryHeader_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCategoryHeader(arg0, await to_candid_CategoryHeader_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setCategoryStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCategoryStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCategoryStatus(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: CustomerInquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_CustomerInquiry_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_CustomerInquiry_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleCategorySlide(arg0: string, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCategorySlide(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCategorySlide(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBannerMessage(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBannerMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBannerMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCarouselRedirect(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCarouselRedirect(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCarouselRedirect(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: CategoryCreate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, await to_candid_CategoryCreate_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, await to_candid_CategoryCreate_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCategoryCarousel(arg0: string, arg1: bigint, arg2: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategoryCarousel(arg0, arg1, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategoryCarousel(arg0, arg1, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateCategoryImages(arg0: string, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategoryImages(arg0, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategoryImages(arg0, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCategoryPrimaryImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategoryPrimaryImage(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategoryPrimaryImage(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCategorySlide(arg0: string, arg1: bigint, arg2: CarouselSlide): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategorySlide(arg0, arg1, await to_candid_CarouselSlide_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategorySlide(arg0, arg1, await to_candid_CarouselSlide_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: ProductUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, await to_candid_ProductUpdate_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, await to_candid_ProductUpdate_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSiteContent(arg0: SiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(arg0);
            return result;
        }
    }
}
async function from_candid_CarouselSlide_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarouselSlide): Promise<CarouselSlide> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_CategoryHeader_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryHeader): Promise<CategoryHeader> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Promise<Category> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerInquiry_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerInquiry): CustomerInquiry {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ProductMedia_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductMedia): Promise<ProductMedia> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Promise<Category | null> {
    return value.length === 0 ? null : await from_candid_Category_n23(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryHeader]): Promise<CategoryHeader | null> {
    return value.length === 0 ? null : await from_candid_CategoryHeader_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: _ExternalBlob;
    images: Array<_ExternalBlob>;
}): Promise<{
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: ExternalBlob;
    images: Array<ExternalBlob>;
}> {
    return {
        displayOrder: value.displayOrder,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        primaryImage: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.primaryImage),
        images: await from_candid_vec_n26(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redirectUrl: string;
    image: _ExternalBlob;
}): Promise<{
    redirectUrl: string;
    image: ExternalBlob;
}> {
    return {
        redirectUrl: value.redirectUrl,
        image: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: bigint;
    enabled: boolean;
    visualContent: _ExternalBlob;
    urlRedirect: string;
}): Promise<{
    order: bigint;
    enabled: boolean;
    visualContent: ExternalBlob;
    urlRedirect: string;
}> {
    return {
        order: value.order,
        enabled: value.enabled,
        visualContent: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.visualContent),
        urlRedirect: value.urlRedirect
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customer: Principal;
    name: string;
    email: string;
    message: string;
    response: [] | [string];
}): {
    id: string;
    customer: Principal;
    name: string;
    email: string;
    message: string;
    response?: string;
} {
    return {
        id: value.id,
        customer: value.customer,
        name: value.name,
        email: value.email,
        message: value.message,
        response: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.response))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    totalPriceInCents: bigint;
    customer: Principal;
    productId: string;
    cancellable: boolean;
    timestamp: bigint;
    upiId: string;
    quantity: bigint;
    shippingAddress: _ShippingAddress;
}): {
    id: string;
    status: OrderStatus;
    totalPriceInCents: bigint;
    customer: Principal;
    productId: string;
    cancellable: boolean;
    timestamp: bigint;
    upiId: string;
    quantity: bigint;
    shippingAddress: ShippingAddress;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n46(_uploadFile, _downloadFile, value.status),
        totalPriceInCents: value.totalPriceInCents,
        customer: value.customer,
        productId: value.productId,
        cancellable: value.cancellable,
        timestamp: value.timestamp,
        upiId: value.upiId,
        quantity: value.quantity,
        shippingAddress: value.shippingAddress
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: _ProductMedia;
    inStock: boolean;
    name: string;
    createdAt: _Time;
    description: string;
    gender: _Gender;
    category: string;
    priceInCents: bigint;
}): Promise<{
    id: string;
    media: ProductMedia;
    inStock: boolean;
    name: string;
    createdAt: Time;
    description: string;
    gender: Gender;
    category: string;
    priceInCents: bigint;
}> {
    return {
        id: value.id,
        media: await from_candid_ProductMedia_n51(_uploadFile, _downloadFile, value.media),
        inStock: value.inStock,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        gender: from_candid_Gender_n54(_uploadFile, _downloadFile, value.gender),
        category: value.category,
        priceInCents: value.priceInCents
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: [] | [_ExternalBlob];
    images: Array<_ExternalBlob>;
}): Promise<{
    video?: ExternalBlob;
    images: Array<ExternalBlob>;
}> {
    return {
        video: record_opt_to_undefined(await from_candid_opt_n53(_uploadFile, _downloadFile, value.video)),
        images: await from_candid_vec_n26(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _CategoryHeader]): Promise<[string, CategoryHeader]> {
    return [
        value[0],
        await from_candid_CategoryHeader_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: {
        reason: string;
    };
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): {
    __kind__: "shipped";
    shipped: null;
} | {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "confirmed";
    confirmed: null;
} {
    return "shipped" in value ? {
        __kind__: "shipped",
        shipped: value.shipped
    } : "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "delivered" in value ? {
        __kind__: "delivered",
        delivered: value.delivered
    } : "confirmed" in value ? {
        __kind__: "confirmed",
        confirmed: value.confirmed
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boys: null;
} | {
    girls: null;
}): Gender {
    return "boys" in value ? Gender.boys : "girls" in value ? Gender.girls : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n58(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Promise<Array<Category>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Category_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _CategoryHeader]>): Promise<Array<[string, CategoryHeader]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarouselSlide>): Promise<Array<CarouselSlide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CarouselSlide_n32(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerInquiry>): Array<CustomerInquiry> {
    return value.map((x)=>from_candid_CustomerInquiry_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n44(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n49(_uploadFile, _downloadFile, x)));
}
async function to_candid_CarouselSlide_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarouselSlide): Promise<_CarouselSlide> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_CategoryCreate_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryCreate): Promise<_CategoryCreate> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_CategoryHeader_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryHeader): Promise<_CategoryHeader> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerInquiry_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInquiry): _CustomerInquiry {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductCreate_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCreate): Promise<_ProductCreate> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductMedia_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductMedia): Promise<_ProductMedia> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductUpdate_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdate): Promise<_ProductUpdate> {
    return await to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: bigint;
    enabled: boolean;
    visualContent: ExternalBlob;
    urlRedirect: string;
}): Promise<{
    order: bigint;
    enabled: boolean;
    visualContent: _ExternalBlob;
    urlRedirect: string;
}> {
    return {
        order: value.order,
        enabled: value.enabled,
        visualContent: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.visualContent),
        urlRedirect: value.urlRedirect
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: ProductMedia;
    inStock: boolean;
    name: string;
    description: string;
    gender: Gender;
    category: string;
    priceInCents: bigint;
}): Promise<{
    id: string;
    media: _ProductMedia;
    inStock: boolean;
    name: string;
    description: string;
    gender: _Gender;
    category: string;
    priceInCents: bigint;
}> {
    return {
        id: value.id,
        media: await to_candid_ProductMedia_n16(_uploadFile, _downloadFile, value.media),
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        gender: to_candid_Gender_n18(_uploadFile, _downloadFile, value.gender),
        category: value.category,
        priceInCents: value.priceInCents
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video?: ExternalBlob;
    images: Array<ExternalBlob>;
}): Promise<{
    video: [] | [_ExternalBlob];
    images: Array<_ExternalBlob>;
}> {
    return {
        video: value.video ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.video)) : candid_none(),
        images: await to_candid_vec_n11(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redirectUrl: string;
    image: ExternalBlob;
}): Promise<{
    redirectUrl: string;
    image: _ExternalBlob;
}> {
    return {
        redirectUrl: value.redirectUrl,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customer: Principal;
    name: string;
    email: string;
    message: string;
    response?: string;
}): {
    id: string;
    customer: Principal;
    name: string;
    email: string;
    message: string;
    response: [] | [string];
} {
    return {
        id: value.id,
        customer: value.customer,
        name: value.name,
        email: value.email,
        message: value.message,
        response: value.response ? candid_some(value.response) : candid_none()
    };
}
async function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media?: ProductMedia;
    inStock?: boolean;
    name?: string;
    description?: string;
    gender?: Gender;
    category?: string;
    priceInCents?: bigint;
}): Promise<{
    media: [] | [_ProductMedia];
    inStock: [] | [boolean];
    name: [] | [string];
    description: [] | [string];
    gender: [] | [_Gender];
    category: [] | [string];
    priceInCents: [] | [bigint];
}> {
    return {
        media: value.media ? candid_some(await to_candid_ProductMedia_n16(_uploadFile, _downloadFile, value.media)) : candid_none(),
        inStock: value.inStock ? candid_some(value.inStock) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        gender: value.gender ? candid_some(to_candid_Gender_n18(_uploadFile, _downloadFile, value.gender)) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        priceInCents: value.priceInCents ? candid_some(value.priceInCents) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: ExternalBlob;
    images: Array<ExternalBlob>;
}): Promise<{
    displayOrder: bigint;
    name: string;
    description: string;
    isActive: boolean;
    primaryImage: _ExternalBlob;
    images: Array<_ExternalBlob>;
}> {
    return {
        displayOrder: value.displayOrder,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        primaryImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.primaryImage),
        images: await to_candid_vec_n11(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    boys: null;
} | {
    girls: null;
} {
    return value == Gender.boys ? {
        boys: null
    } : value == Gender.girls ? {
        girls: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "shipped";
    shipped: null;
} | {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "confirmed";
    confirmed: null;
}): {
    shipped: null;
} | {
    cancelled: {
        reason: string;
    };
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value.__kind__ === "shipped" ? {
        shipped: value.shipped
    } : value.__kind__ === "cancelled" ? {
        cancelled: value.cancelled
    } : value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "delivered" ? {
        delivered: value.delivered
    } : value.__kind__ === "confirmed" ? {
        confirmed: value.confirmed
    } : value;
}
async function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
